services:
 db:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: Pass@123
   MYSQL_DATABASE: mydb

  ports:
      - 3306
 wordpress:
  image: wordpress
  ports:
   - 80:80  
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: Pass@123
    WORDPRESS_DB_NAME: mydb

